import { primeTime } from "./medium/primeTime.js";
//console.log(primeTime(65536));
import { runLength } from "./medium/runLength.js";
//console.log(runLength("wwwrrhg"));
import { primeMover } from "./medium/primeMover.js";
//console.log(primeMover(23));
import { stringScramble } from "./medium/stringScramble.js";
//console.log(stringScramble(["rkqodlw","world"]));
import { caeserChiper } from "./medium/caeserChiper.js";
//console.log(caeserChiper("ATTACKATONCE",4));
import { simpleMode } from "./medium/simpleMode.js";
//console.log(simpleMode([5,5,10,6,5,10,10]));
import { consecutive } from "./medium/consecutive.js";
//console.log(consecutive([4,8,6,11]));
import { formattedDivision } from "./medium/formattedDivision.js";
//console.log(formattedDivision(123123456789,10000));
import { permutationStep } from "./medium/permutationStep.js";
//console.log(permutationStep(1111121));
