import { primeTime } from "./medium/primeTime.js";
//console.log(primeTime(65536));
import { runLength } from "./medium/runLength.js";
//console.log(runLength("wwwrrhg"));
import { primeMover } from "./medium/primeMover.js";
//console.log(primeMover(23));
import { stringScramble } from "./medium/stringScramble.js";
//console.log(stringScramble(["rkqodlw","world"]));
import { caeserChiper } from "./medium/caeserChiper.js";
//console.log(caeserChiper("ATTACKATONCE",4));
import { simpleMode } from "./medium/simpleMode.js";
//console.log(simpleMode([5,5,10,6,5,10,10]));
import { consecutive } from "./medium/consecutive.js";
//console.log(consecutive([4,8,6,11]));
import { formattedDivision } from "./medium/formattedDivision.js";
//console.log(formattedDivision(123123456789,10000));
import { permutationStep } from "./medium/permutationStep.js";
//console.log(permutationStep(1111121));
import { dashInsert2 } from "./medium/dashInsert2.js";
//console.log(dashInsert2("4546793"));
import { tripleDouble } from "./medium/tripleDouble.js";
//console.log(tripleDouble(4519999277,41177722899));
import { stringReduction } from "./medium/stringReduction.js";
//console.log(stringReduction("bcab"));
import { threeFive } from "./medium/threeFive.js";
//console.log(threeFive(10));
import { fibonacciChecker } from "./medium/fibonacciChecker.js";
//console.log(fibonacciChecker(8944394323791464));
import { nthFibonacciNumber } from "./medium/nthFibonacciNumber.js";
//console.log(nthFibonacciNumber(10));
import { multipleBrackets } from "./medium/multipleBrackets.js";
console.log(multipleBrackets("((hello! [world]))"));
